// Auto-generated by LibreLane
module Reorder_buffer(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input reset,
  input clk,
  input[1:0] control,
  input[3:0] value,
  input[31:0] value0,
  input[31:0] value1,
  input[31:0] value2,
  input[2:0] enable_write,
  input[3:0] write_location0,
  input[3:0] write_location1,
  input[3:0] write_location2,
  output[31:0] out,
  output[3:0] data_location,
  output success,
  output done
);
endmodule
