// Auto-generated by LibreLane
module FP32_Div(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input signa,
  input signb,
  input[7:0] expa,
  input[7:0] expb,
  input[22:0] mantisaA,
  input[22:0] mantisaB,
  output sign,
  output[7:0] exp,
  output[22:0] mantisa
);
endmodule
