// Auto-generated by LibreLane
module FPU_32_controller(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input[31:0] a,
  input[31:0] b,
  input[31:0] c,
  input[3:0] operand,
  output stall,
  output done,
  output[31:0] final_out
);
endmodule
